# Copyright 2025 WALA community. All rights reserved.
# Licensed under the MIT License, Version 1.0 (the "License");
# Implemented by [Jinhui YE / HKUST University] in [2025].

"""
WALA Framework with optional RGB-D parallel LAM pretraining.

Depth design in this file:
  - Depth Anything V2 is used only to produce depth maps from RGB images.
  - The transition bottleneck consumes depth maps at pixel/patch level, not
    Depth Anything's RGB-DINO hidden features.
  - RGB/DINO transition and pixel-depth transition are fused into one canonical
    transition-token sequence.
  - Downstream VLA still uses a single transition-token target. Inference does
    not require depth.
"""
import os
import sys
from dataclasses import dataclass, field
from typing import List, Optional, Tuple
from contextlib import nullcontext

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image

from WALA.utils.image import resize_images, to_pil_preserve
from WALA.model.tools import FRAMEWORK_REGISTRY
from WALA.utils.logging import initialize_overwatch

logger = initialize_overwatch(__name__)

# HuggingFace Default / LLaMa-2 IGNORE_INDEX (for labels)
IGNORE_INDEX = -100

from WALA.model.framework.base_framework import baseframework
from WALA.model.framework.share_tools import merge_framework_config
from WALA.model.modules.action_model.ActionHead import get_action_model
from WALA.model.modules.vlm import get_vlm_model

from WALA.model.modules.dino_model.dinov3 import get_dino_model


from WALA.model.modules.world_model.LAM import (
    ContinuousTransitionBottleneckTokenizer,
    LatentActionToTransitionTokens,
)


# ──────────────────────────────────────────────────────────────────────
#  Default Config for WALA
#  - Documents every framework-level parameter with type + description
#  - YAML values override these defaults; extra YAML keys are preserved
# ──────────────────────────────────────────────────────────────────────
@dataclass
class WALADefaultConfig:
    """WALA framework default parameters.

    All fields can be overridden by the corresponding key in the YAML
    ``framework:`` section. Extra YAML keys not listed here are kept
    as-is (Config-as-API flexibility).
    """

    # --- Registry identifier (must match @FRAMEWORK_REGISTRY.register) ---
    name: str = "WALA"

    # === VLM backbone (Qwen2.5-VL / Qwen3-VL) ===
    qwenvl: dict = field(default_factory=lambda: {
        "base_vlm": os.environ.get("WALA_BASE_VLM", "./pretrained/Qwen3-VL-4B-Instruct-Action"),
        "attn_implementation": "sdpa",
    })

    # === Action head (MLP regression over action special tokens) ===
    action_model: dict = field(default_factory=lambda: {
        "action_model_type": "MLP",
        "action_dim": 14,
        "state_dim": 14,
        "action_hidden_dim": 2560,
        "condition_dim": 1024,
        "future_action_window_size": 49,
        "past_action_window_size": 0,
    })

    # === DINO Vision Encoder ===
    dino: dict = field(default_factory=lambda: {
        "dino_backbone": os.environ.get("WALA_DINOV3_PATH", "./pretrained/dinov3-vitb16-pretrain-lvd1689m"),
    })

    # === Continuous Transition Bottleneck Tokenizer ===
    transition_bottleneck: dict = field(default_factory=lambda: {
        # "vla": normal VLA training; "pretrain": transition bottleneck pretraining
        "training_mode": "vla",

        # DINO patch feature dimension.
        "dino_dim": 768,

        # Number of compact transition tokens produced by the tokenizer.
        "num_transition_tokens": 32,

        # Keep this much smaller than the VLM hidden size to avoid a huge tokenizer.
        "hidden_dim": 1024,

        "encoder_layers": 8,
        "decoder_layers": 4,
        "latent_resampler_layers": 1,
        "num_heads": 8,
        "max_future_steps": 64,
        "max_patches": 1024,
        "max_action_tokens": 256,

        # Optional RGB-D parallel LAM.
        # Depth maps are generated by Depth Anything and consumed at pixel/patch level.
        "use_depth": False,
        "depth_loss_weight": 1.0,
        "depth_fusion_scale": 1.0,
        "depth_anything_encoder": "vitl",
        "depth_anything_ckpt": "",
        "depth_anything_input_size": 224,
        "depth_patch_size": 16,

        # Pretraining losses for transition bottleneck.
        "smooth_l1_weight": 1.0,
        "cosine_weight": 0.1,
        "composition_weight": 0, # 0.1,
        "reencode_weight": 0, # 0.1,
        "content_invariance_weight": 0, # 0.05,
        "content_aug_scale_std": 0.05,
        "content_aug_bias_std": 0.02,
        "min_composition_steps": 2,

        # Loss weights used in normal VLA training.
        "use_transition_alignment": False,
        "transition_alignment_loss_weight": 0.01,
        "transition_alignment_l1_weight": 0.1,

        "use_transition_decode": True,
        "transition_decode_loss_weight": 0.1,
        "transition_decode_cosine_weight": 0.1,
        "transition_decode_use_all_future": True,
        "depth_decoder_loss_weight": 0.5,
        "depth_gradient_loss_weight": 0.2,
        "depth_decoder_use_all_future": True,

        # VLA-stage parameter control.
        "freeze_encoder_in_vla": True,
        "train_decoder_in_vla": True,
    })

    # === Observation image size (optional resize before encoding) ===
    # Set to [H, W] to resize; None = keep original resolution.
    obs_image_size: Optional[list] = None


@FRAMEWORK_REGISTRY.register("WALA")
class WALAFramework(baseframework):
    """
    Multimodal vision-language-action model (OFT variant).

    Modes:
      - transition_bottleneck.training_mode = "pretrain": train the LAM tokenizer.
      - transition_bottleneck.training_mode = "vla": train VLA with transition-token supervision.

    Optional depth path:
      - Enable with framework.transition_bottleneck.use_depth=True.
      - Depth Anything is used only to generate depth maps.
      - The transition bottleneck fuses RGB/DINO and pixel-depth transitions.
      - Inference does not use depth.
    """

    # ------------------------------------------------------------------
    # Temporary debug visualization settings. Delete after testing.
    # ------------------------------------------------------------------
    DEBUG_VIS_ENABLE = False
    DEBUG_VIS_DIR = os.environ.get("WALA_DEBUG_VIS_DIR", "./debug_vis")
    DEBUG_VIS_MAX = 64
    DEBUG_VIS_ITEMS = 2
    DEBUG_VIS_T = -1
    DEBUG_VIS_OVERLAY_ALPHA = 0.6

    def __init__(
        self,
        config: Optional[dict] = None,
        **kwargs,
    ) -> None:
        super().__init__()
        self.config = merge_framework_config(WALADefaultConfig, config)
        self.qwen_vl_interface = get_vlm_model(config=self.config)

        # Align action_hidden_dim to VLM hidden_size at runtime.
        self.config.framework.action_model.action_hidden_dim = self.qwen_vl_interface.model.config.hidden_size
        self.action_model = get_action_model(config=self.config)

        self.action_model_type = str(
            self.config.framework.action_model.action_model_type
        ).strip()

        act_cfg = self.config.framework.action_model
        dino_cfg = self.config.framework.dino
        ft_cfg = self.config.framework.transition_bottleneck

        self.future_action_window_size = act_cfg.future_action_window_size
        self.past_action_window_size = act_cfg.past_action_window_size
        self.chunk_len = 1 + self.future_action_window_size

        self.action_token = "🔍"
        self.action_token_id = self.qwen_vl_interface.processor.tokenizer(
            "🔍", add_special_tokens=False
        )["input_ids"][0]

        self.num_transition_tokens = getattr(
            ft_cfg,
            "num_transition_tokens",
            getattr(ft_cfg, "num_future_tokens", self.chunk_len),
        )
        self.dino_feature_dim = getattr(ft_cfg, "dino_dim", 768)
        self.transition_hidden_dim = getattr(ft_cfg, "hidden_dim", self.dino_feature_dim)

        self.l1_loss = nn.L1Loss()

        # Frozen DINO feature extractor / target provider.
        self.dino_encoder = get_dino_model(backone_name=dino_cfg.dino_backbone)
        for param in self.dino_encoder.parameters():
            param.requires_grad = False

        # Optional Depth Anything V2 depth-map generator.
        self.use_depth_lam = getattr(ft_cfg, "use_depth", False)
        self.depth_anything = None
        if self.use_depth_lam:
            _DEPTH_ANYTHING_ROOT = os.path.abspath(
                os.path.join(
                    os.path.dirname(__file__),
                    "..",
                    "..",
                    "third_party",
                    "Depth-Anything-V2",
                )
            )

            if _DEPTH_ANYTHING_ROOT not in sys.path:
                sys.path.insert(0, _DEPTH_ANYTHING_ROOT)

            from depth_anything_v2.dpt import DepthAnythingV2

            da_encoder = getattr(ft_cfg, "depth_anything_encoder", "vitl")
            model_configs = {
                "vits": {"encoder": "vits", "features": 64, "out_channels": [48, 96, 192, 384]},
                "vitb": {"encoder": "vitb", "features": 128, "out_channels": [96, 192, 384, 768]},
                "vitl": {"encoder": "vitl", "features": 256, "out_channels": [256, 512, 1024, 1024]},
                "vitg": {"encoder": "vitg", "features": 384, "out_channels": [1536, 1536, 1536, 1536]},
            }
            if da_encoder not in model_configs:
                raise ValueError(f"Unsupported depth_anything_encoder={da_encoder!r}.")

            self.depth_anything = DepthAnythingV2(**model_configs[da_encoder])
            ckpt = getattr(ft_cfg, "depth_anything_ckpt", None)
            if ckpt is None or ckpt == "":
                ckpt = os.path.join(
                    _DEPTH_ANYTHING_ROOT,
                    "checkpoints",
                    f"depth_anything_v2_{da_encoder}.pth",
                )
            elif not os.path.isabs(ckpt):
                ckpt = os.path.abspath(ckpt)
            self.depth_anything.load_state_dict(torch.load(ckpt, map_location="cpu"))
            self.depth_anything.eval()
            for p in self.depth_anything.parameters():
                p.requires_grad = False

        # Continuous Transition Bottleneck: future-to-transition tokenizer.
        self.transition_bottleneck = ContinuousTransitionBottleneckTokenizer(
            dino_dim=self.dino_feature_dim,
            hidden_dim=self.transition_hidden_dim,
            num_transition_tokens=self.num_transition_tokens,
            encoder_layers=getattr(ft_cfg, "encoder_layers", 8),
            decoder_layers=getattr(ft_cfg, "decoder_layers", 4),
            num_heads=ft_cfg.num_heads,
            max_future_steps=ft_cfg.max_future_steps,
            max_patches=ft_cfg.max_patches,
            smooth_l1_weight=ft_cfg.smooth_l1_weight,
            cosine_weight=ft_cfg.cosine_weight,
            composition_weight=getattr(ft_cfg, "composition_weight", 0),
            reencode_weight=getattr(ft_cfg, "reencode_weight", 0),
            content_invariance_weight=getattr(ft_cfg, "content_invariance_weight", 0),
            content_aug_scale_std=getattr(ft_cfg, "content_aug_scale_std", 0.05),
            content_aug_bias_std=getattr(ft_cfg, "content_aug_bias_std", 0.02),
            min_composition_steps=getattr(ft_cfg, "min_composition_steps", 2),
            use_depth=getattr(ft_cfg, "use_depth", False),
            depth_loss_weight=getattr(ft_cfg, "depth_loss_weight", 1.0),
            depth_gradient_loss_weight=getattr(ft_cfg, "depth_gradient_loss_weight", 0.2),
            depth_fusion_scale=getattr(ft_cfg, "depth_fusion_scale", 1.0),
            depth_patch_size=getattr(ft_cfg, "depth_patch_size", 16),
        )

        # Project / resample VLA action-token hidden states into transition-token space.
        self.latent_action_to_transition_tokens_for_encoder = LatentActionToTransitionTokens(
            action_dim=act_cfg.action_hidden_dim,
            transition_dim=self.transition_hidden_dim,
            num_transition_tokens=self.num_transition_tokens,
            num_layers=getattr(ft_cfg, "latent_resampler_layers", 1),
            num_heads=ft_cfg.num_heads,
            max_action_tokens=getattr(ft_cfg, "max_action_tokens", 256),
        )

        self.latent_action_to_transition_tokens_for_decoder = LatentActionToTransitionTokens(
            action_dim=act_cfg.action_hidden_dim,
            transition_dim=self.transition_hidden_dim,
            num_transition_tokens=self.num_transition_tokens,
            num_layers=getattr(ft_cfg, "latent_resampler_layers", 1),
            num_heads=ft_cfg.num_heads,
            max_action_tokens=getattr(ft_cfg, "max_action_tokens", 256),
        )

        # Avoid unused-parameter issues under DDP by freezing modules that are not
        # supposed to be optimized in each training stage.
        _ft_mode = getattr(ft_cfg, "training_mode", "vla")
        if _ft_mode in {"pretrain", "transition_bottleneck_pretrain", "transition_pretrain"}:
            # Pretrain only the transition bottleneck.
            for module in [
                self.qwen_vl_interface,
                self.action_model,
                self.latent_action_to_transition_tokens_for_encoder,
                self.latent_action_to_transition_tokens_for_decoder,
            ]:
                for param in module.parameters():
                    param.requires_grad = False
        else:
            if getattr(ft_cfg, "freeze_encoder_in_vla", True):
                self._set_transition_encoder_requires_grad(False)

            if not getattr(ft_cfg, "train_decoder_in_vla", True):
                self._set_transition_decoder_requires_grad(False)
                self._set_transition_depth_decoder_requires_grad(False)

    # ------------------------------------------------------------------
    # Parameter freezing helpers
    # ------------------------------------------------------------------
    def _set_transition_encoder_requires_grad(self, requires_grad: bool) -> None:
        """
        Freeze/unfreeze the target encoder and its shared representation stems.

        time_embed, patch_embed, and depth_current_patch_proj are also used by
        decoders, but are kept on the frozen side so the pretrained target-token
        coordinate system remains fixed during VLA training.
        """
        encoder_modules = [
            self.transition_bottleneck.current_input_proj,
            self.transition_bottleneck.delta_input_proj,
            self.transition_bottleneck.encoder,
        ]
        for module in encoder_modules:
            for param in module.parameters():
                param.requires_grad = requires_grad

        encoder_params = [
            self.transition_bottleneck.transition_queries,
            self.transition_bottleneck.transition_token_embed,
            self.transition_bottleneck.current_type_embed,
            self.transition_bottleneck.delta_type_embed,
            self.transition_bottleneck.time_embed,
            self.transition_bottleneck.patch_embed,
        ]
        for param in encoder_params:
            param.requires_grad = requires_grad

        if getattr(self.transition_bottleneck, "use_depth", False):
            depth_encoder_modules = [
                "depth_current_patch_proj",
                "depth_delta_patch_proj",
                "depth_encoder",
                "rgb_depth_cross_fuse",
                "rgb_depth_fuse",
            ]
            for name in depth_encoder_modules:
                module = getattr(self.transition_bottleneck, name, None)
                if module is not None:
                    for param in module.parameters():
                        param.requires_grad = requires_grad

            depth_encoder_params = [
                "depth_transition_queries",
                "depth_transition_token_embed",
                "depth_current_type_embed",
                "depth_delta_type_embed",
            ]
            for name in depth_encoder_params:
                param = getattr(self.transition_bottleneck, name, None)
                if param is not None:
                    param.requires_grad = requires_grad

    def _set_transition_decoder_requires_grad(self, requires_grad: bool) -> None:
        """Freeze/unfreeze RGB decoder-only modules."""
        decoder_modules = [
            self.transition_bottleneck.horizon_decoder,
            self.transition_bottleneck.current_patch_proj,
            self.transition_bottleneck.transition_film,
            self.transition_bottleneck.delta_head,
        ]
        for module in decoder_modules:
            for param in module.parameters():
                param.requires_grad = requires_grad

        decoder_params = [
            self.transition_bottleneck.horizon_query,
        ]
        for param in decoder_params:
            param.requires_grad = requires_grad

    def _set_transition_depth_decoder_requires_grad(self, requires_grad: bool) -> None:
        """Freeze/unfreeze depth decoder-only modules."""
        if not getattr(self.transition_bottleneck, "use_depth", False):
            return

        depth_decoder_modules = [
            "depth_spatial_decoder",
            "depth_decode_patch_proj",
            "depth_patch_film",
            "depth_patch_pixel_head",
            "depth_dense_refine",
        ]
        for name in depth_decoder_modules:
            module = getattr(self.transition_bottleneck, name, None)
            if module is not None:
                for param in module.parameters():
                    param.requires_grad = requires_grad

    # ------------------------------------------------------------------
    # Data preparation
    # ------------------------------------------------------------------
    def _build_training_visual_inputs(self, examples: List[dict]):
        batch_images = [example["image"] for example in examples]
        instructions = [example["lang"] for example in examples]
        actions = [example.get("action", None) for example in examples]

        def safe_get_cur(imgs, idx):
            """Safely extract current frame [-1] for a view."""
            try:
                return imgs[idx][0][-1]
            except Exception:
                return None

        def safe_get_seq(imgs, view_idx, seq_idx):
            """Safely extract a sequence: seq_idx=0 past/current, seq_idx=1 future."""
            try:
                seq = imgs[view_idx][seq_idx]
                return seq if isinstance(seq, list) else [seq]
            except Exception:
                return None

        valid_pc_len, valid_f_len = 1, 1
        for imgs in batch_images:
            pc = safe_get_seq(imgs, 0, 0) or safe_get_seq(imgs, 1, 0) or safe_get_seq(imgs, 2, 0)
            if pc is not None:
                valid_pc_len = len(pc)
            fut = safe_get_seq(imgs, 0, 1) or safe_get_seq(imgs, 1, 1) or safe_get_seq(imgs, 2, 1)
            if fut is not None:
                valid_f_len = len(fut)
            if pc is not None and fut is not None:
                break
        
        processed_batch_images = []
        head_past_and_current_images = []
        head_future_images = []

        for images in batch_images:
            h_cur = safe_get_cur(images, 0)
            l_cur = safe_get_cur(images, 1)
            r_cur = safe_get_cur(images, 2)

            ref_img = h_cur or l_cur or r_cur
            if ref_img is not None:
                blank_img = Image.new(ref_img.mode, ref_img.size, color=0)
            else:
                blank_img = Image.new("RGB", (224, 224), color=0)

            processed_batch_images.append([
                h_cur or blank_img,
                l_cur or blank_img,
                r_cur or blank_img,
            ])

            head_past_and_current_images.append(safe_get_seq(images, 0, 0) or [blank_img] * valid_pc_len)
            head_future_images.append(safe_get_seq(images, 0, 1) or [blank_img] * valid_f_len)

        train_obs_image_size = getattr(self.config.framework, "obs_image_size", None)
        if train_obs_image_size:
            processed_batch_images = resize_images(processed_batch_images, target_size=train_obs_image_size)
            head_past_and_current_images = resize_images(head_past_and_current_images, train_obs_image_size)
            head_future_images = resize_images(head_future_images, train_obs_image_size)

        return processed_batch_images, instructions, actions, head_past_and_current_images, head_future_images

    def _encode_dino_current_and_future(
        self,
        head_past_and_current_images: List[list],
        head_future_images: List[list],
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        B = len(head_past_and_current_images)

        dino_input_of_past_and_current = self.dino_encoder.prepare_dino_input(head_past_and_current_images)
        dino_input_of_future = self.dino_encoder.prepare_dino_input(head_future_images)

        with torch.no_grad(), torch.autocast("cuda", dtype=torch.bfloat16):
            dino_feat_pc = self.dino_encoder(dino_input_of_past_and_current)
            dino_feat_future = self.dino_encoder(dino_input_of_future)

        dino_feat_pc = dino_feat_pc.float()
        dino_feat_future = dino_feat_future.float()

        _, L_dino, H_dino = dino_feat_pc.shape
        N_pc = dino_feat_pc.shape[0] // B
        assert N_pc >= 1, f"DINO 当前帧特征切分失败，N_pc={N_pc}。"

        dino_feat_pc = dino_feat_pc.view(B, N_pc, L_dino, H_dino)
        dino_feature_current = dino_feat_pc[:, -1, :, :]

        _, L_future, H_future = dino_feat_future.shape
        N_future = dino_feat_future.shape[0] // B
        assert N_future >= 1, f"DINO 未来帧特征切分失败，N_future={N_future}。"
        assert L_future == L_dino and H_future == H_dino, (
            f"DINO 当前/未来特征维度不一致: current=({L_dino}, {H_dino}), "
            f"future=({L_future}, {H_future})"
        )

        dino_feature_future = dino_feat_future.view(B, N_future, L_future, H_future)
        return dino_feature_current, dino_feature_future

    # ------------------------------------------------------------------
    # Depth extraction
    # ------------------------------------------------------------------
    @torch.no_grad()
    def _infer_depth_anything_pil(self, img: Image.Image) -> torch.Tensor:
        """Run Depth Anything on a PIL image and return a depth map tensor [H, W]."""
        if self.depth_anything is None:
            raise RuntimeError("Depth Anything is not initialized. Set transition_bottleneck.use_depth=True.")

        ft_cfg = self.config.framework.transition_bottleneck
        input_size = getattr(ft_cfg, "depth_anything_input_size", 224)

        if not isinstance(img, Image.Image):
            img = to_pil_preserve(img)

        rgb = np.array(img.convert("RGB"))
        bgr = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)

        # Do not call infer_image() directly: its image2tensor() chooses a generic
        # cuda device, which can mismatch the current DDP rank. We move the input
        # to the actual Depth Anything parameter device explicitly.
        image, (h, w) = self.depth_anything.image2tensor(bgr, input_size)
        da_device = next(self.depth_anything.parameters()).device
        image = image.to(device=da_device, dtype=torch.float32)

        ctx = torch.autocast("cuda", dtype=torch.bfloat16) if da_device.type == "cuda" else nullcontext()
        with ctx:
            depth = self.depth_anything.forward(image)

        depth = F.interpolate(
            depth[:, None].float(),
            (h, w),
            mode="bilinear",
            align_corners=True,
        )[0, 0]

        # os.makedirs("./debug_depth", exist_ok=True)
        # if not hasattr(self, "_debug_depth_save_count"):
        #     self._debug_depth_save_count = 0
        # if self._debug_depth_save_count < 16:
        #     depth_vis = depth.detach().float().cpu()
        #     depth_vis = torch.nan_to_num(depth_vis)
        #     depth_vis = (depth_vis - depth_vis.min()) / (depth_vis.max() - depth_vis.min() + 1e-6)
        #     depth_vis = (depth_vis * 255).clamp(0, 255).byte().numpy()
        #     Image.fromarray(depth_vis).save(
        #         f"./debug_depth/depth_{self._debug_depth_save_count:04d}.png"
        #     )
        #     img.convert("RGB").save(
        #         f"./debug_depth/rgb_{self._debug_depth_save_count:04d}.png"
        #     )
        #     self._debug_depth_save_count += 1

        return depth.detach().float()

    @torch.no_grad()
    def _depth_maps_from_image_sequences(self, image_sequences: List[list]) -> torch.Tensor:
        """
        Convert PIL image sequences to Depth Anything depth maps.

        image_sequences: List length B, each item is List[PIL.Image] length N
        return: [B, N, H, W], torch.float32 on current model device
        """
        if self.depth_anything is None:
            raise RuntimeError("Depth Anything is not initialized. Set transition_bottleneck.use_depth=True.")

        B = len(image_sequences)
        if B == 0:
            raise ValueError("image_sequences is empty.")
        N = len(image_sequences[0])

        all_depths = []
        for seq in image_sequences:
            if len(seq) != N:
                raise ValueError("All image sequences should have the same length after padding/resizing.")

            seq_depths = []
            for img in seq:
                seq_depths.append(self._infer_depth_anything_pil(img).cpu())
            all_depths.append(torch.stack(seq_depths, dim=0))

        depth = torch.stack(all_depths, dim=0)
        device = next(self.parameters()).device
        return depth.to(device=device, dtype=torch.float32)

    def _encode_depth_current_and_future(
        self,
        head_past_and_current_images: List[list],
        head_future_images: List[list],
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Return:
          current_depth: [B, H, W]
          future_depth:  [B, T, H, W]
        """
        depth_pc = self._depth_maps_from_image_sequences(head_past_and_current_images)
        depth_future = self._depth_maps_from_image_sequences(head_future_images)
        current_depth = depth_pc[:, -1, :, :]
        return current_depth, depth_future

    # ------------------------------------------------------------------
    # Text/state formatting
    # ------------------------------------------------------------------
    def _format_state_as_text(self, state) -> str:
        if state is None:
            return ""

        if torch.is_tensor(state):
            arr = state.detach().cpu().float().numpy()
        else:
            arr = np.asarray(state, dtype=np.float32)

        arr = np.squeeze(arr)
        if arr.ndim == 0:
            arr = arr.reshape(1)
        elif arr.ndim > 1:
            arr = arr[-1].reshape(-1)
        else:
            arr = arr.reshape(-1)

        arr = np.clip(arr, -1.0, 1.0)
        q = np.round((arr + 1.0) * 255 / 2).astype(np.uint8)
        items = [str(int(v)) for v in q]
        return " The current discretized robot proprioceptive state is: [" + ",".join(items) + "]."

    # ------------------------------------------------------------------
    # Temporary debug visualization helpers. Delete after testing.
    # ------------------------------------------------------------------
    def _debug_vis_enabled_rank0(self) -> bool:
        if not self.DEBUG_VIS_ENABLE:
            return False
        if torch.distributed.is_available() and torch.distributed.is_initialized():
            return torch.distributed.get_rank() == 0
        return True

    def _debug_u8(self, x: np.ndarray) -> np.ndarray:
        x = np.nan_to_num(x.astype(np.float32))
        lo, hi = np.percentile(x, [1, 99])
        if hi <= lo:
            hi = lo + 1e-6
        return np.clip((x - lo) / (hi - lo) * 255.0, 0, 255).astype(np.uint8)

    def _debug_label(self, img: np.ndarray, text: str) -> np.ndarray:
        out = img.copy()
        cv2.rectangle(out, (0, 0), (190, 24), (0, 0, 0), -1)
        cv2.putText(out, text, (6, 17), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1)
        return out

    def _debug_depth_rgb(self, depth: torch.Tensor, out_hw: tuple) -> np.ndarray:
        d = depth.detach().float().cpu().numpy()
        g = self._debug_u8(d)
        gray = np.stack([g, g, g], axis=-1)
        if gray.shape[:2] != out_hw:
            gray = cv2.resize(gray, (out_hw[1], out_hw[0]), interpolation=cv2.INTER_NEAREST)
        return gray

    def _debug_dino_pca_triplet(
        self,
        current_feat: torch.Tensor,
        pred_future_feat: torch.Tensor,
        gt_future_feat: torch.Tensor,
        out_hw: tuple,
    ) -> tuple:
        current = current_feat.detach().float().cpu().numpy()
        pred = pred_future_feat.detach().float().cpu().numpy()
        gt = gt_future_feat.detach().float().cpu().numpy()

        # PCA basis 用 current GT + future GT 拟合，不让 pred 影响颜色坐标系。
        ref = np.concatenate([current, gt], axis=0)
        mean = ref.mean(axis=0, keepdims=True)
        ref0 = ref - mean
        _, _, vt = np.linalg.svd(ref0, full_matrices=False)
        comp = vt[:3].T

        current_rgb = (current - mean) @ comp
        pred_rgb = (pred - mean) @ comp
        gt_rgb = (gt - mean) @ comp

        # 归一化范围也只用 GT reference，避免 pred 异常值污染颜色尺度。
        ref_rgb = np.concatenate([current_rgb, gt_rgb], axis=0)
        lo = np.percentile(ref_rgb, 1, axis=0, keepdims=True)
        hi = np.percentile(ref_rgb, 99, axis=0, keepdims=True)

        def to_rgb_img(x: np.ndarray) -> np.ndarray:
            x = ((x - lo) / (hi - lo + 1e-6)).clip(0.0, 1.0)
            x = (x * 255.0).astype(np.uint8)
            ph, pw = self.transition_bottleneck._infer_square_patch_hw(x.shape[0])
            x = x.reshape(ph, pw, 3)
            return cv2.resize(x, (out_hw[1], out_hw[0]), interpolation=cv2.INTER_NEAREST)

        return to_rgb_img(current_rgb), to_rgb_img(pred_rgb), to_rgb_img(gt_rgb)

    def _debug_overlay(self, rgb: np.ndarray, pca_rgb: np.ndarray) -> np.ndarray:
        alpha = float(self.DEBUG_VIS_OVERLAY_ALPHA)
        return (
            (1.0 - alpha) * rgb.astype(np.float32)
            + alpha * pca_rgb.astype(np.float32)
        ).clip(0, 255).astype(np.uint8)

    def _debug_crop_letterbox(self, img: np.ndarray) -> np.ndarray:
        """
        Crop black padding caused by resizing AxB into a square image.
        """
        h, w = img.shape[:2]

        expected_h = int(round(w * 700.0 / 1080.0))
        if expected_h < h:
            top = (h - expected_h) // 2
            bottom = top + expected_h
            return img[top:bottom, ...]

        expected_w = int(round(h * 1080.0 / 700.0))
        if expected_w < w:
            left = (w - expected_w) // 2
            right = left + expected_w
            return img[:, left:right, ...]

        return img

    @torch.no_grad()
    def _debug_save_vla_prediction_vis(
        self,
        head_past_and_current_images: List[list],
        head_future_images: List[list],
        current_dino: torch.Tensor,
        pred_dino_future: torch.Tensor,
        gt_dino_future: torch.Tensor,
        current_depth: torch.Tensor,
        pred_depth_future: torch.Tensor,
        gt_depth_future: torch.Tensor,
    ) -> None:
        if not self._debug_vis_enabled_rank0():
            return

        os.makedirs(self.DEBUG_VIS_DIR, exist_ok=True)

        count = getattr(self, "_debug_vis_count", 0)
        if count >= self.DEBUG_VIS_MAX:
            return

        bsz, t_total = gt_dino_future.shape[:2]
        t = self.DEBUG_VIS_T if self.DEBUG_VIS_T >= 0 else t_total + self.DEBUG_VIS_T
        t = max(0, min(t, t_total - 1))

        for b in range(min(bsz, self.DEBUG_VIS_ITEMS)):
            if count >= self.DEBUG_VIS_MAX:
                break

            current_rgb = np.array(head_past_and_current_images[b][-1].convert("RGB"))
            future_rgb = np.array(head_future_images[b][t].convert("RGB"))
            out_hw = future_rgb.shape[:2]

            if current_rgb.shape[:2] != out_hw:
                current_rgb = cv2.resize(
                    current_rgb,
                    (out_hw[1], out_hw[0]),
                    interpolation=cv2.INTER_CUBIC,
                )

            current_pca_rgb, pred_dino_rgb, gt_dino_rgb = self._debug_dino_pca_triplet(
                current_dino[b],
                pred_dino_future[b, t],
                gt_dino_future[b, t],
                out_hw,
            )

            current_overlay = self._debug_overlay(current_rgb, current_pca_rgb)
            pred_overlay = self._debug_overlay(future_rgb, pred_dino_rgb)
            gt_overlay = self._debug_overlay(future_rgb, gt_dino_rgb)

            current_depth_rgb = self._debug_depth_rgb(current_depth[b], out_hw)
            pred_depth_rgb = self._debug_depth_rgb(pred_depth_future[b, t], out_hw)
            gt_depth_rgb = self._debug_depth_rgb(gt_depth_future[b, t], out_hw)

            current_overlay = self._debug_crop_letterbox(current_overlay)
            current_depth_rgb = self._debug_crop_letterbox(current_depth_rgb)
            pred_overlay = self._debug_crop_letterbox(pred_overlay)
            gt_overlay = self._debug_crop_letterbox(gt_overlay)
            pred_depth_rgb = self._debug_crop_letterbox(pred_depth_rgb)
            gt_depth_rgb = self._debug_crop_letterbox(gt_depth_rgb)

            panel = np.concatenate(
                [
                    current_overlay,
                    current_depth_rgb,
                    pred_overlay,
                    gt_overlay,
                    pred_depth_rgb,
                    gt_depth_rgb,
                ],
                axis=1,
            )

            stem = f"debug_{count:05d}_b{b}_t{t}"
            Image.fromarray(panel).save(os.path.join(self.DEBUG_VIS_DIR, f"{stem}_panel.png"))

            # np.savez_compressed(
            #     os.path.join(self.DEBUG_VIS_DIR, f"{stem}.npz"),
            #     current_dino=current_dino[b].detach().float().cpu().numpy(),
            #     pred_dino=pred_dino_future[b, t].detach().float().cpu().numpy(),
            #     gt_dino=gt_dino_future[b, t].detach().float().cpu().numpy(),
            #     current_depth=current_depth[b].detach().float().cpu().numpy(),
            #     pred_depth=pred_depth_future[b, t].detach().float().cpu().numpy(),
            #     gt_depth=gt_depth_future[b, t].detach().float().cpu().numpy(),
            # )

            count += 1

        self._debug_vis_count = count

    # ------------------------------------------------------------------
    # Forward routers
    # ------------------------------------------------------------------
    def forward(
        self,
        examples: List[dict] = None,
        **kwargs,
    ) -> Tuple:
        mode = kwargs.get("training_mode", kwargs.get("mode", None))
        if mode is None:
            mode = getattr(self.config.framework.transition_bottleneck, "training_mode", "vla")

        if mode in {"pretrain", "transition_bottleneck_pretrain", "transition_pretrain"}:
            return self.forward_transition_bottleneck_pretrain(examples=examples, **kwargs)
        return self.forward_vla(examples=examples, **kwargs)

    def forward_transition_bottleneck_pretrain(
        self,
        examples: List[dict] = None,
        **kwargs,
    ) -> Tuple:
        """
        Pretrain the continuous transition bottleneck.
        This path does not run Qwen-VL or action prediction.
        """
        _, _, _, head_past_and_current_images, head_future_images = self._build_training_visual_inputs(examples)

        dino_feature_current, dino_feature_future = self._encode_dino_current_and_future(
            head_past_and_current_images=head_past_and_current_images,
            head_future_images=head_future_images,
        )

        current_depth = None
        future_depth = None
        if getattr(self.config.framework.transition_bottleneck, "use_depth", False):
            current_depth, future_depth = self._encode_depth_current_and_future(
                head_past_and_current_images=head_past_and_current_images,
                head_future_images=head_future_images,
            )

        with torch.autocast("cuda", dtype=torch.bfloat16):
            tokenizer_out = self.transition_bottleneck(
                dino_feature_current.float(),
                dino_feature_future.float(),
                current_depth=current_depth,
                future_depth=future_depth,
            )

        total_loss = tokenizer_out["loss"]
        zero = total_loss.detach() * 0.0

        return {
            "transition_bottleneck_loss": tokenizer_out["loss"],
            "transition_bottleneck_recon_loss": tokenizer_out["recon_loss"],
            "transition_bottleneck_cosine_loss": tokenizer_out["cosine_loss"],
            "transition_bottleneck_composition_loss": tokenizer_out["composition_loss"],
            "transition_bottleneck_reencode_loss": tokenizer_out["reencode_loss"],
            "transition_bottleneck_content_invariance_loss": tokenizer_out["content_invariance_loss"],
            "transition_bottleneck_depth_recon_loss": tokenizer_out.get("depth_recon_loss", zero),
            "total_loss": total_loss,
        }

    def forward_vla(
        self,
        examples: List[dict] = None,
        **kwargs,
    ) -> Tuple:
        batch_images, instructions, actions, head_past_and_current_images, head_future_images = \
            self._build_training_visual_inputs(examples)

        states = [example.get("state", None) for example in examples]
        state_texts = [self._format_state_as_text(state) for state in states]

        valid_indices = [i for i, a in enumerate(actions) if a is not None]

        action_tokens = self.action_token * self.chunk_len
        prompt_suffix = f" Please predict the next {self.chunk_len} robot actions: <action>{action_tokens}<action>."
        instructions = [
            instruction + state_text + prompt_suffix
            for instruction, state_text in zip(instructions, state_texts)
        ]

        dino_feature_current, dino_feature_future = self._encode_dino_current_and_future(
            head_past_and_current_images=head_past_and_current_images,
            head_future_images=head_future_images,
        )

        qwen_inputs = self.qwen_vl_interface.build_qwenvl_inputs(images=batch_images, instructions=instructions)
        with torch.autocast("cuda", dtype=torch.bfloat16):
            qwenvl_outputs = self.qwen_vl_interface(
                **qwen_inputs,
                output_attentions=False,
                output_hidden_states=True,
                return_dict=True,
            )
            last_hidden = qwenvl_outputs.hidden_states[-1]

        with torch.autocast("cuda", dtype=torch.bfloat16):
            input_ids = qwen_inputs.get("input_ids", None)

            latent_action = self._gather_token_embeddings(
                last_hidden, input_ids, self.action_token_id, self.chunk_len
            )

            transition_alignment_loss = 0.0 * latent_action.sum()
            transition_alignment_cosine_loss = 0.0 * latent_action.sum()
            transition_alignment_l1_loss = 0.0 * latent_action.sum()
            transition_depth_decode_loss = 0.0 * latent_action.sum()  # [MODIFIED]
            transition_depth_decode_pixel_loss = 0.0 * latent_action.sum()
            transition_depth_decode_grad_loss = 0.0 * latent_action.sum()

            current_depth = None  # [MODIFIED]
            future_depth = None  # [MODIFIED]
            if getattr(self.config.framework.transition_bottleneck, "use_depth", False):  # [MODIFIED]
                current_depth, future_depth = self._encode_depth_current_and_future(  # [MODIFIED]
                    head_past_and_current_images=head_past_and_current_images,
                    head_future_images=head_future_images,
                )

            if getattr(self.config.framework.transition_bottleneck, "use_transition_alignment", True):
                with torch.no_grad():
                    target_transition_tokens = self.transition_bottleneck.encode(
                        dino_feature_current.float(),
                        dino_feature_future.float(),
                        current_depth=current_depth,
                        future_depth=future_depth,
                    )
                pred_transition_tokens_for_encoder = self.latent_action_to_transition_tokens_for_encoder(latent_action)
                target_transition_tokens = target_transition_tokens.detach().float()

                pred_norm = F.normalize(pred_transition_tokens_for_encoder.float(), dim=-1)
                target_norm = F.normalize(target_transition_tokens, dim=-1)
                transition_alignment_cosine_loss = 1.0 - (pred_norm * target_norm).sum(dim=-1).mean()

                pred_ln = F.layer_norm(
                    pred_transition_tokens_for_encoder.float(),
                    pred_transition_tokens_for_encoder.shape[-1:],
                )
                target_ln = F.layer_norm(target_transition_tokens, target_transition_tokens.shape[-1:])
                transition_alignment_l1_loss = F.smooth_l1_loss(pred_ln, target_ln)

                alignment_l1_w = getattr(
                    self.config.framework.transition_bottleneck,
                    "transition_alignment_l1_weight",
                    0.1,
                )
                transition_alignment_loss = transition_alignment_cosine_loss + alignment_l1_w * transition_alignment_l1_loss

            transition_decode_loss = 0.0 * latent_action.sum()
            transition_decode_l1_loss = 0.0 * latent_action.sum()
            transition_decode_cosine_loss = 0.0 * latent_action.sum()

            if getattr(self.config.framework.transition_bottleneck, "use_transition_decode", True):
                target_delta = (
                    dino_feature_future.float()
                    - dino_feature_current[:, None, :, :].float()
                ).detach()

                pred_transition_tokens_for_decoder = self.latent_action_to_transition_tokens_for_decoder(latent_action)

                pred_delta = self.transition_bottleneck.decode_delta(
                    dino_feature_current.float(),
                    pred_transition_tokens_for_decoder.float(),
                    num_future_steps=dino_feature_future.shape[1],
                )

                if getattr(self.config.framework.transition_bottleneck, "transition_decode_use_all_future", True):
                    pred_delta_for_loss = pred_delta.float()
                    target_delta_for_loss = target_delta.float()
                else:
                    pred_delta_for_loss = pred_delta[:, -1, :, :].float()
                    target_delta_for_loss = target_delta[:, -1, :, :].float()

                transition_decode_l1_loss = F.l1_loss(pred_delta_for_loss, target_delta_for_loss)

                pred_delta_norm = F.normalize(pred_delta_for_loss.float(), dim=-1)
                target_delta_norm = F.normalize(target_delta_for_loss.float(), dim=-1)
                transition_decode_cosine_loss = 1.0 - (pred_delta_norm * target_delta_norm).sum(dim=-1).mean()

                decode_cos_w = getattr(
                    self.config.framework.transition_bottleneck,
                    "transition_decode_cosine_weight",
                    0.1,
                )

                # [MODIFIED] Also supervise dense depth reconstruction in VLA decoder stage.
                if getattr(self.config.framework.transition_bottleneck, "use_depth", False):
                    B, T, L, _ = dino_feature_future.shape
                    depth_patch_hw = self.transition_bottleneck._infer_square_patch_hw(L)

                    current_depth_norm, future_depth_norm = self.transition_bottleneck._normalize_depth_clip(
                        current_depth=current_depth.to(device=dino_feature_current.device),
                        future_depth=future_depth.to(device=dino_feature_current.device),
                    )

                    target_depth_delta = (
                        future_depth_norm - current_depth_norm[:, None, :, :]
                    ).detach()

                    pred_depth_delta = self.transition_bottleneck._decode_dense_depth_delta(
                        current_depth=current_depth_norm,
                        transition_tokens=pred_transition_tokens_for_decoder.float(),
                        num_future_steps=T,
                        patch_hw=depth_patch_hw,
                    )

                    if self._debug_vis_enabled_rank0():
                        pred_dino_future = (
                            dino_feature_current[:, None, :, :].float()
                            + pred_delta.float()
                        ).detach()

                        pred_depth_future = (
                            current_depth_norm[:, None, :, :].float()
                            + pred_depth_delta.float()
                        ).detach()

                        self._debug_save_vla_prediction_vis(
                            head_past_and_current_images=head_past_and_current_images,
                            head_future_images=head_future_images,
                            current_dino=dino_feature_current.float().detach(),
                            pred_dino_future=pred_dino_future,
                            gt_dino_future=dino_feature_future.float().detach(),
                            current_depth=current_depth_norm.float().detach(),
                            pred_depth_future=pred_depth_future,
                            gt_depth_future=future_depth_norm.float().detach(),
                        )

                    if getattr(self.config.framework.transition_bottleneck, "depth_decoder_use_all_future", True):
                        pred_depth_delta_for_loss = pred_depth_delta.float()
                        target_depth_delta_for_loss = target_depth_delta.float()
                    else:
                        pred_depth_delta_for_loss = pred_depth_delta[:, -1, :, :].float()
                        target_depth_delta_for_loss = target_depth_delta[:, -1, :, :].float()

                    transition_depth_decode_pixel_loss = F.smooth_l1_loss(
                        pred_depth_delta_for_loss,
                        target_depth_delta_for_loss,
                    )
                    transition_depth_decode_grad_loss = self.transition_bottleneck._depth_gradient_l1_loss(
                        pred_depth_delta_for_loss,
                        target_depth_delta_for_loss,
                    )
                    depth_grad_w = getattr(
                        self.config.framework.transition_bottleneck,
                        "depth_gradient_loss_weight",
                        0.2,
                    )
                    transition_depth_decode_loss = (
                        transition_depth_decode_pixel_loss
                        + depth_grad_w * transition_depth_decode_grad_loss
                    )

                depth_decode_w = getattr(self.config.framework.transition_bottleneck, "depth_decoder_loss_weight", 0.5)

                transition_decode_loss = (
                    transition_decode_l1_loss
                    + decode_cos_w * transition_decode_cosine_loss
                    + depth_decode_w * transition_depth_decode_loss
                )

            transition_alignment_w = getattr(
                self.config.framework.transition_bottleneck,
                "transition_alignment_loss_weight",
                0.01,
            )
            transition_decode_w = getattr(
                self.config.framework.transition_bottleneck,
                "transition_decode_loss_weight",
                0.1,
            )

        with torch.autocast("cuda", dtype=torch.float32):
            if len(valid_indices) > 0:
                latent_action = latent_action.float()
                pred_transition_tokens_for_encoder = pred_transition_tokens_for_encoder.float()
                pred_transition_tokens_for_decoder = pred_transition_tokens_for_decoder.float()
                valid_actions = [actions[i] for i in valid_indices]
                valid_latent_action = latent_action[valid_indices]
                valid_pred_transition_tokens_for_encoder = pred_transition_tokens_for_encoder[valid_indices]
                valid_pred_transition_tokens_for_decoder = pred_transition_tokens_for_decoder[valid_indices]

                actions_tensor = torch.tensor(
                    np.array(valid_actions), device=latent_action.device, dtype=latent_action.dtype
                )
                assert actions_tensor.shape[1] >= self.chunk_len, (
                    f"Action sequence length ({actions_tensor.shape[1]}) is shorter than "
                    f"chunk_len ({self.chunk_len}). Please check your config and data alignment."
                )
                actions_target = actions_tensor[:, -self.chunk_len:, :]
                if self.action_model_type == "MLP":
                    action_loss = self.action_model(valid_latent_action, actions_target)
                elif self.action_model_type == "Transformer":
                    use_auxiliary_conditions = (
                        getattr(self.config.framework.transition_bottleneck, "use_transition_alignment", True)
                        and getattr(self.config.framework.transition_bottleneck, "use_transition_decode", True)
                    )
                    if use_auxiliary_conditions:
                        auxiliary_conditions = torch.cat(
                            [
                                valid_pred_transition_tokens_for_encoder.detach(),
                                valid_pred_transition_tokens_for_decoder.detach(),
                            ],
                            dim=1,
                        )
                    else:
                        auxiliary_conditions = None
                    action_loss = self.action_model(
                        valid_latent_action,
                        actions=actions_target,
                        condition_tokens=auxiliary_conditions,
                    )
                else:
                    raise NotImplementedError
            else:
                action_loss = 0.0 * latent_action.mean()

            total_loss = (
                action_loss.float()
                + transition_alignment_w * transition_alignment_loss.float()
                + transition_decode_w * transition_decode_loss.float()
            )

        return {
            "action_loss": action_loss,
            "transition_alignment_loss": transition_alignment_loss,
            "transition_alignment_cosine_loss": transition_alignment_cosine_loss,
            "transition_alignment_l1_loss": transition_alignment_l1_loss,
            "transition_decode_loss": transition_decode_loss,
            "transition_decode_l1_loss": transition_decode_l1_loss,
            "transition_decode_cosine_loss": transition_decode_cosine_loss,
            "transition_depth_decode_loss": transition_depth_decode_loss,  # [MODIFIED]
            "transition_depth_decode_pixel_loss": transition_depth_decode_pixel_loss,
            "transition_depth_decode_grad_loss": transition_depth_decode_grad_loss,
            "total_loss": total_loss,
        }

    @torch.inference_mode()
    def predict_action(
        self,
        examples: List[dict] = None,
        **kwargs: str,
    ) -> dict:
        """
        Inference forward: predict future actions from current multi-view images and instruction.
        Inference does not use DINO/Depth/LAM targets.
        """
        if type(examples) is not list:
            examples = [examples]

        B = len(examples)
        if B > 1:
            valid_indices = []
            valid_examples = []
            valid_actions = []

            for i, example in enumerate(examples):
                act = example.get("action", None)
                if act is not None:
                    valid_indices.append(i)
                    valid_examples.append(example)
                    valid_actions.append(act)

            if len(valid_indices) == 0:
                return {"normalized_actions": np.array([])}

            examples = valid_examples

        batch_images = [to_pil_preserve(example["image"]) for example in examples]
        instructions = [example["lang"] for example in examples]

        states = [example.get("state", None) for example in examples]
        state_texts = [self._format_state_as_text(state) for state in states]

        def safe_get(imgs, idx):
            try:
                return imgs[idx][0][-1]
            except Exception:
                return None

        processed_batch_images = []
        for images in batch_images:
            head = safe_get(images, 0)
            left = safe_get(images, 1)
            right = safe_get(images, 2)

            ref_img = head or left or right
            if ref_img is not None:
                blank_img = Image.new(ref_img.mode, ref_img.size, color=0)
            else:
                blank_img = Image.new("RGB", (224, 224), color=0)

            processed_batch_images.append([
                head or blank_img,
                left or blank_img,
                right or blank_img,
            ])

        batch_images = processed_batch_images

        train_obs_image_size = getattr(self.config.framework, "obs_image_size", None)
        if train_obs_image_size:
            batch_images = resize_images(batch_images, target_size=train_obs_image_size)

        action_tokens = self.action_token * self.chunk_len
        prompt_suffix = f" Please predict the next {self.chunk_len} robot actions: <action>{action_tokens}<action>."
        instructions = [
            instruction + state_text + prompt_suffix
            for instruction, state_text in zip(instructions, state_texts)
        ]

        qwen_inputs = self.qwen_vl_interface.build_qwenvl_inputs(images=batch_images, instructions=instructions)
        with torch.autocast("cuda", dtype=torch.bfloat16):
            qwenvl_outputs = self.qwen_vl_interface(
                **qwen_inputs,
                output_attentions=False,
                output_hidden_states=True,
                return_dict=True,
            )
            last_hidden = qwenvl_outputs.hidden_states[-1]
            input_ids = qwen_inputs.get("input_ids", None)
            latent_action = self._gather_token_embeddings(
                last_hidden, input_ids, self.action_token_id, self.chunk_len
            )

            use_auxiliary_conditions = (
                getattr(self.config.framework.transition_bottleneck, "use_transition_alignment", True)
                and getattr(self.config.framework.transition_bottleneck, "use_transition_decode", True)
            )
            if use_auxiliary_conditions:
                pred_transition_tokens_for_encoder = self.latent_action_to_transition_tokens_for_encoder(latent_action)
                pred_transition_tokens_for_decoder = self.latent_action_to_transition_tokens_for_decoder(latent_action)

        with torch.autocast("cuda", dtype=torch.float32):
            latent_action = latent_action.float()
    
            if self.action_model_type == "MLP":
                pred_actions = self.action_model.predict_action(latent_action)
            elif self.action_model_type == "Transformer":
                if use_auxiliary_conditions:
                    pred_transition_tokens_for_encoder = pred_transition_tokens_for_encoder.float()
                    pred_transition_tokens_for_decoder = pred_transition_tokens_for_decoder.float()
                    auxiliary_conditions = torch.cat(
                        [
                            pred_transition_tokens_for_encoder.detach(),
                            pred_transition_tokens_for_decoder.detach(),
                        ],
                        dim=1,
                    )
                else:
                    auxiliary_conditions = None
                pred_actions = self.action_model.predict_action(
                    latent_action,
                    condition_tokens=auxiliary_conditions,
                )

        normalized_actions = pred_actions.detach().cpu().numpy()
        return {"normalized_actions": normalized_actions}

    def _gather_token_embeddings(
        self,
        last_hidden: torch.Tensor,
        input_ids: torch.Tensor,
        token_id: int,
        expected_len: int,
    ) -> torch.Tensor:
        """Extract the hidden states at special token positions."""
        device = input_ids.device
        B, L, H = last_hidden.shape
        mask = input_ids == token_id

        counts = mask.sum(dim=1)
        if (counts < expected_len).any():
            raise RuntimeError(f"Token ID {token_id} 数量不足 (预期 {expected_len})")

        idx = torch.arange(L, device=device).unsqueeze(0).expand(B, L)
        masked_pos = torch.where(mask, idx, torch.full_like(idx, -1))
        topk_pos = masked_pos.topk(k=expected_len, dim=-1).values
        selected_pos = topk_pos.sort(dim=-1).values

        expanded_index = selected_pos.unsqueeze(-1).expand(-1, -1, H)
        return last_hidden.gather(dim=1, index=expanded_index)
